---
title: "Huddle_SPC"
author: "A Gruer"
date: "26 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(qicharts2)
library(lubridate)
library(readxl)


```

```{r getdata}
huddle_data_raw <- read_xlsx("data/Copy of TABLE_HUDDLE DATA - SCREEN 01.xlsx",
                             sheet = "2018-19")


```

```{r wrangle data}
#wide to long clean up dates-----------
huddle_data <- huddle_data_raw %>%
                select(-X__2) %>%
                rename(kpi = X__1) %>%
                gather(key="date", value="value", -kpi) %>%
                mutate(date_original = date, #1
                       date=stringr::str_remove(date,"__1"), #2
                       date=as.numeric(date),#3
                       date=as.Date(date,origin="1899/12/30"), #4 
                       date=if_else(date_original=="1_Aug",as.Date("2018/08/01"),date)) %>% #5
                filter(date < as.Date("2018/10/27"))



#1 store orignal excel numeric date string
#2 some strings had a trailing __1 , remove that part
#3 convert excel date numeric string to a number
#4 convert number to string excle start counting form 1899/12/30
#5 one of the date columns in the original spreadsheet had 1_aug harcoded 



#map kpis to categories and remove categpry header rows----------
#indexes of categoriy row headers on one day
cat_start <- 
huddle_data %>% filter(date == as.Date("2018/10/25")) %>%
  pull(value) %>%
  is.na() %>%
  which() 

#end of range of rows for each category
 cat_end <- lead(cat_start, default = 71) - 1
 #category names
 category <-  huddle_data[huddle_data$date== as.Date("2018/10/25") & is.na(huddle_data$value),1, drop = TRUE ]

# map over the three vectors, for heach header create a dataframe of the rows it applies to
 #row bind into a data frame
categories <- pmap_dfr(list(start = cat_start,
          end = cat_end,
          categor = category),
     function(start,end,category){

        tibble(row = seq(start,end) ,
               category = category)
     })

#create a lookup table between kpi and category
  
 lookup <- tibble(kpi= huddle_data[huddle_data$date== as.Date("2018/10/25") ,1 , drop = TRUE],
                 category = categories[,2,drop = TRUE])
 
 #join to huddle data on kpi and bring across the category
 #filter out category headers
 huddle_data <- huddle_data %>%
   left_join(lookup) %>%
   filter(!kpi %in% category)

 #replace RAG codes with numeric representation------------
 huddle_data <- 
   huddle_data %>%
   mutate(value = case_when(
                    value == "G" ~ "1",
                    value == "A" ~ "0",
                    value == "R" ~ "-1",
                    value == "-" ~ NA_character_,
                    TRUE ~ value)) %>%
   mutate(value = as.numeric(value)) 
 
 #replace ed 4 hour stay greater than 1 with proportion
huddle_data <- 
  huddle_data %>%
   mutate(value = if_else(kpi == "ED STAY 4 HOUR TARGET" & value > 1,
                          value / 100, value))

 
```


```{r ed presentations}
huddle_data %>%
  filter(kpi == "ED PRESENTATIONS") %>%
  filter(!is.na(value)) %>%
 tail(150) %>%
  qic(x = seq_along( date),
      y = value,
      data = .,
      chart = "c",
      title = "SPC 'C' Chart of ED Presentations past 150 week days")

  #ggplot(aes(value)) +
  #geom_histogram(binwidth = 25)
```

```{r ed 4 hour stay}
huddle_data %>%
  filter(kpi == "ED STAY 4 HOUR TARGET") %>%
  filter(!is.na(value)) %>%

 # ggplot(aes(value)) +
  #geom_histogram(binwidth = 0.05)
 tail(100) %>%
  qic(x = seq_along( date),
      y = value,
      data = .,
      chart = "i",
      title = "SPC 'I' Chart of ED Four Hour Stay % past 150 week days")

  
```